name: eliana_partner
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fusca_branco:
    path: ./packages/fusca_branco

  cupertino_icons: ^1.0.2
  flutter_modular: ^4.5.0
  flutter_keyboard_visibility: ^5.2.0
  flutter_hooks: ^0.18.2+1
  flutter_triple: ^1.2.7+2
  flare_flutter: ^3.0.2
  dartz: ^0.10.1
  shared_preferences: ^2.0.13
  oktoast: ^3.1.5
  dio: ^4.0.4
  hasura_connect: ^4.0.0+2
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - .env
